# Production docker-compose override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  backend:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 512M

  worker:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 2G

