# Development-only docker-compose override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    volumes:
      # Mount only source code for hot reload
      - ./packages/server/src:/app/src
      - ./packages/server/uploads:/app/uploads
      - ./packages/server/temp:/app/temp
      # Explicitly exclude node_modules to prevent architecture conflicts
      - backend_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run start:dev

  worker:
    volumes:
      - ./packages/worker:/app
      - ./packages/server/uploads:/data/uploads
      - ./packages/server/temp:/data/temp
      # Exclude Python cache
      - /app/__pycache__

volumes:
  backend_node_modules:

